export const cardsConfig = new Map ([ 
  ["main", [
    { word: 'actionA', img: './img/cry.jpg'},
    { word: 'actionB', img: './img/dance.jpg'},
    { word: 'animalA', img: './img/cat.jpg'},
    { word: 'animalB', img: './img/bird.jpg'},
    { word: 'clothes', img: './img/pants.jpg'},
    { word: 'emotions', img: './img/smile.jpg'},
    { word: 'business', img: './img/business.jpg'},
    { word: 'web', img: './img/optimization.png'},
  ]],
  ["actionA", [
    { word: 'cry', translation: 'плакать', img: './img/cry.jpg', audioSrc: './audio/cry.mp3' },
    { word: 'dance', translation: 'танцевать', img: './img/dance.jpg', audioSrc: './audio/dance.mp3' },
    { word: 'dive', translation: 'нырять', img: './img/dive.jpg', audioSrc: './audio/dive.mp3' },
    { word: 'draw', translation: 'рисовать', img: './img/draw.jpg', audioSrc: './audio/draw.mp3' },
    { word: 'fish', translation: 'ловить рыбу', img: './img/fish.jpg', audioSrc: './audio/fish.mp3' },
    { word: 'fly', translation: 'летать', img: './img/fly.jpg', audioSrc: './audio/fly.mp3' },
    { word: 'hug', translation: 'обнимать', img: './img/hug.jpg', audioSrc: './audio/hug.mp3' },
    { word: 'jump', translation: 'прыгать', img: './img/jump.jpg', audioSrc: './audio/jump.mp3' },
  ]],
  ["actionB", [
    { word: 'open', translation: 'открывать', img: './img/open.jpg', audioSrc: './audio/open.mp3' },
    { word: 'play', translation: 'играть', img: './img/play.jpg', audioSrc: './audio/play.mp3' },
    { word: 'point', translation: 'указывать', img: './img/point.jpg', audioSrc: './audio/point.mp3' },
    { word: 'ride', translation: 'ездить', img: './img/ride.jpg', audioSrc: './audio/ride.mp3' },
    { word: 'run', translation: 'бегать', img: './img/run.jpg', audioSrc: './audio/run.mp3' },
    { word: 'sing', translation: 'петь', img: './img/sing.jpg', audioSrc: './audio/sing.mp3' },
    { word: 'skip', translation: 'скакать', img: './img/skip.jpg', audioSrc: './audio/skip.mp3' },
    { word: 'swim', translation: 'плавать', img: './img/swim.jpg', audioSrc: './audio/swim.mp3' },
  ]],
  ["animalA", [
    { word: 'cat', translation: 'кот', img: './img/cat.jpg', audioSrc: './audio/cat.mp3' },
    { word: 'chick', translation: 'цыплёнок', img: './img/chick.jpg', audioSrc: './audio/chick.mp3' },
    { word: 'chicken', translation: 'курица', img: './img/chicken.jpg', audioSrc: './audio/chicken.mp3' },
    { word: 'dog', translation: 'пёс', img: './img/dog.jpg', audioSrc: './audio/dog.mp3' },
    { word: 'horse', translation: 'конь', img: './img/horse.jpg', audioSrc: './audio/horse.mp3' },
    { word: 'pig', translation: 'свин', img: './img/pig.jpg', audioSrc: './audio/pig.mp3' },
    { word: 'rabbit', translation: 'кролик', img: './img/rabbit.jpg', audioSrc: './audio/rabbit.mp3' },
    { word: 'sheep', translation: 'овечка', img: './img/sheep.jpg', audioSrc: './audio/sheep.mp3' },
  ]],
  ["animalB", [
    { word: 'bird', translation: 'птичка', img: './img/bird.jpg', audioSrc: './audio/bird.mp3' },
    { word: 'fish', translation: 'рыбка', img: './img/fish.jpg', audioSrc: './audio/fish.mp3' },
    { word: 'frog', translation: 'лягушка', img: './img/frog.jpg', audioSrc: './audio/frog.mp3' },
    { word: 'giraffe', translation: 'жираф', img: './img/giraffe.jpg', audioSrc: './audio/giraffe.mp3' },
    { word: 'lion', translation: 'лев', img: './img/lion.jpg', audioSrc: './audio/lion.mp3' },
    { word: 'mouse', translation: 'мышь', img: './img/mouse.jpg', audioSrc: './audio/mouse.mp3' },
    { word: 'turtle', translation: 'черепаха', img: './img/turtle.jpg', audioSrc: './audio/turtle.mp3' },
    { word: 'dolphin', translation: 'дельфин', img: './img/dolphin.jpg', audioSrc: './audio/dolphin.mp3' },
  ]],
  ["clothes", [
    { word: 'skirt', translation: 'юбка', img: './img/skirt.jpg', audioSrc: './audio/skirt.mp3' },
    { word: 'pants', translation: 'штаны', img: './img/pants.jpg', audioSrc: './audio/pants.mp3' },
    { word: 'blouse', translation: 'блузка', img: './img/blouse.jpg', audioSrc: './audio/blouse.mp3' },
    { word: 'dress', translation: 'платье', img: './img/dress.jpg', audioSrc: './audio/dress.mp3' },
    { word: 'shirt', translation: 'рубашка', img: './img/shirt.jpg', audioSrc: './audio/shirt.mp3' },
    { word: 'boot', translation: 'ботинки', img: './img/boot.jpg', audioSrc: './audio/boot.mp3' },
    { word: 'coat', translation: 'пальто', img: './img/coat.jpg', audioSrc: './audio/coat.mp3' },
    { word: 'shoe', translation: 'обувь', img: './img/shoe.jpg', audioSrc: './audio/shoe.mp3' },
  ]],
  ["emotions", [
    { word: 'sad', translation: 'грусть', img: './img/sad.jpg', audioSrc: './audio/sad.mp3' },
    { word: 'angry', translation: 'злость', img: './img/angry.jpg', audioSrc: './audio/angry.mp3' },
    { word: 'happy', translation: 'радость', img: './img/happy.jpg', audioSrc: './audio/happy.mp3' },
    { word: 'tired', translation: 'усталость', img: './img/tired.jpg', audioSrc: './audio/tired.mp3' },
    { word: 'surprised', translation: 'удивление', img: './img/surprised.jpg', audioSrc: './audio/surprised.mp3' },
    { word: 'scared', translation: 'страх', img: './img/scared.jpg', audioSrc: './audio/scared.mp3' },
    { word: 'smile', translation: 'улыбка', img: './img/smile.jpg', audioSrc: './audio/smile.mp3' },
    { word: 'laugh', translation: 'смех', img: './img/laugh.jpg', audioSrc: './audio/laugh.mp3' },
  ]],
  ["business", [
    { word: 'growth', translation: 'рост', img: './img/growth.png', audioSrc: './audio/growth.mp3' },
    { word: 'target', translation: 'цель', img: './img/target.png', audioSrc: './audio/target.mp3' },
    { word: 'money', translation: 'деньги', img: './img/money.png', audioSrc: './audio/money.mp3' },
    { word: 'hierarchy', translation: 'иерархия', img: './img/hierarchy.png', audioSrc: './audio/hierarchy.mp3' },
    { word: 'strategy', translation: 'стратегия', img: './img/strategy.png', audioSrc: './audio/strategy.mp3' },
    { word: 'notebook', translation: 'блокнот', img: './img/notebook.png', audioSrc: './audio/notebook.mp3' },
    { word: 'deal', translation: 'сделка', img: './img/business.jpg', audioSrc: './audio/deal.mp3' },
    { word: 'briefcase', translation: 'портфель', img: './img/briefcase.png', audioSrc: './audio/brief.mp3' },
  ]],
  ["web", [
    { word: 'task manager', translation: 'менеджер задач', img: './img/tm.png', audioSrc: './audio/tm.mp3' },
    { word: 'website', translation: 'вебсайт', img: './img/website.png', audioSrc: './audio/website.mp3' },
    { word: 'error', translation: 'ошибка', img: './img/error.png', audioSrc: './audio/error.mp3' },
    { word: 'mediacontent', translation: 'медиаконтент', img: './img/mediacontent.png', audioSrc: './audio/mediacontent.mp3' },
    { word: 'domain name', translation: 'домен', img: './img/domainname.png', audioSrc: './audio/domainname.mp3' },
    { word: 'notepad', translation: 'блокнот', img: './img/notepad.png', audioSrc: './audio/notepad.mp3' },
    { word: 'social media', translation: 'социальные медиа', img: './img/socialmedia.png', audioSrc: './audio/socialmedia.mp3' },
    { word: 'optimization', translation: 'оптимизация', img: './img/optimization.png', audioSrc: './audio/optimization.mp3' },
  ]],
]);

